# -*- coding: utf-8 -*-
"""nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0sDOSZ6x5aqv-039qyFlG9SL8YwJs9K

# Assignment 1: Pashto Dialects Edit Distance
# Roll No: 22P-9177
"""

# First, the edit distance function


def edit_distance(word1, word2):

    if len(word1) < len(word2):
        word1, word2 = word2, word1

    if len(word2) == 0:
        return len(word1)

    # initial row
    prev = list(range(len(word2) + 1))

    for i, char1 in enumerate(word1):
        current = [i + 1]
        for j, char2 in enumerate(word2):
            insert = prev[j + 1] + 1
            delete = current[j] + 1
            sub = prev[j] + (0 if char1 == char2 else 1)
            current.append(min(insert, delete, sub))
        prev = current

    return prev[-1]

# quick test
print("Test:", edit_distance("tsalor", "tsaler"))
# Now for similarity between two word entries
# Some have multiple words like "waṛīz, čorī" or "myērə stərgā"
# So I split them and take the pair with smallest distance (highest similarity)

def get_similarity(entry1, entry2):
    # split by comma, slash, or spaces
    parts1 = [p.strip() for p in entry1.replace(',', ' ').replace('/', ' ').split() if p.strip()]
    parts2 = [p.strip() for p in entry2.replace(',', ' ').replace('/', ' ').split() if p.strip()]

    if not parts1 or not parts2:
        return 0.0

    best = 0.0
    for p1 in parts1:
        for p2 in parts2:
            dist = edit_distance(p1, p2)
            # I used max length instead of sum because it gives better similarity for different lengths
            max_len = max(len(p1), len(p2))
            if max_len == 0:
                sim = 1.0
            else:
                sim = 1 - (dist / max_len)
            if sim > best:
                best = sim
    return best

print(get_similarity("myērə stərgā", "lmar"))  # should be high for sun word in some dialects


dialects = ["quetta", "harnai", "bannu", "miranshah", "tanai", "khost",
            "sherani", "kandahar", "maidanshahr", "kabul", "peshawar", "marwat"]

words = {
"quetta": ["Pašto", "tsalor", "špaž", "tsənga", "muž", "zmā", "stā", "halək", "nǰiləi", "pša", "lmar", "tsok", "ḍēr zyāt", "ləž", "čšəl", "hagəi", "wo", "yəm", "dzəm", "žəba", "kor", "sta", "yiž", "plār"],

"harnai": ["Pašto", "tsaler", "špož", "tsona", "moš", "mā eghē", "tāgha", "waṛīz, čorī", "čuwara", "ghədəi", "mērə", "čok", "tsaṭ", "ləž", "ghwətəl", "hoya", "wo", "yə", "sə", "žəbā", "kēr", "štā", "yirz", "piyār"],

"bannu": ["Pāštē", "sālēr", "špēž", "sərāng", "miž", "ēmo", "ēto", "wēṛkā", "wēṛkyē", "pšā", "myērə stərgā", "sēk", "pirā zyot", "ləški", "čšəl", "yēya", "ēh", "yə", "tsə", "žəbā", "kēr", "štā", "yiž", "plor"],

"miranshah": ["Pāštē", "tsālwēr", "špēž", "tsərāng", "miž", "ēmo", "ēto", "wēṛkai", "ǰəlkiyē", "pšā", "ghormə stərgā", "tsēk", "rəṭ zyot", "ləški", "čšəl", "yēya", "ēh", "yə", "tsə", "žəbā", "kēr", "štā", "yiž", "plor"],

"tanai": ["Pāx̌tē", "tsālēr", "špēg", "tsərgē", "mig", "ēmo", "ēto", "wēṛkai", "ǰəlkiyē", "px̌ā", "myērə stərgā", "tsēk", "rəṭ zyot", "ləg", "tsəx̌əl", "yēya", "ēh", "yəm", "tsəm", "žəbā", "kēr", "štā", "yig", "plor"],

"khost": ["Pāxto", "tsālwor", "špēg", "tsərāng", "mu", "ēmo", "ēto", "wēṛkai", "wēṛkyē", "pxā", "myērə stərgā", "tsok", "ḍēr zyot", "ləg", "tsəxəl", "woya", "ēh", "yəm", "tsəm", "ǰəba", "kolə", "štā", "yig", "plor"],

"sherani": ["Paṣ̌to", "tsalor", "ʃpaz", "tsənga", "muz", "zmā", "stā", "halək", "nǰiləi", "pʃa", "lmar", "tsok", "ḍēr zyāt", "ləz", "čʃəl", "hagəi", "wo", "yəm", "dzəm", "zəba", "kor", "sta", "yiz", "plār"],

"kandahar": ["Paṣ̌to", "tsalor", "špaẓ̌", "tsənga", "muẓ̌", "zmā", "stā", "halək", "nǰiləi", "pṣ̌a", "lmar", "tsok", "ḍēr zyāt", "ləẓ̌", "čṣ̌əl", "hagəi", "wo", "yəm", "dzəm", "žəba", "kor", "sta", "yiẓ̌", "plār"],

"maidanshahr": ["Pax̌to", "tsalor", "špaγ̌", "tsənga", "muγ̌", "zmâ", "stâ", "halək", "ǰiləi", "px̌a", "lmar", "tsok", "ḍēr zyât", "ləγ̌", "tsəx̌əl", "hagəi", "wo", "yəm", "dzəm", "žəba", "kor", "sta", "yiγ̌", "plâr"],

"kabul": ["Pəxto", "tsalor", "špag", "tsənga", "mung", "zəmā", "stā", "halək", "ǰinəi", "pxa", "nmar", "tsok", "ḍēr zyāt", "ləg", "tskəl", "hagəi/hā", "wo", "yəm", "zəm", "žəba", "kor", "šta", "yig", "plār"],

"peshawar": ["Puxto", "salor", "špag", "singa", "mung", "zamā", "stā", "halək", "ǰinē", "xpa", "nwar", "sok", "ḍēr zyāt", "ləg", "skəl", "hagē/hā", "ao", "yəm", "zəm", "ǰəba", "kor", "šta", "yig", "plār"],

"marwat": ["Paṣ̌to", "čālor", "špaž", "čərānga", "muž", "ēma", "ēta", "zərkayē", "ǰinkiyē", "pša", "lmar", "čok", "ḍēr zyāt", "ləẓ̌", "čšəl", "angəi", "aa", "yə", "ǰəm", "žəba", "kor", "sta", "iž", "plār"]
}

# coordinates for the map
coords = {
"quetta": (66.9749, 30.1798),
"harnai": (67.9374, 30.1044),
"bannu": (70.6454, 32.9909),
"miranshah": (70.1730, 32.9514),
"tanai": (69.8597, 33.3585),
"khost": (70.7517, 33.8094),
"sherani": (70.0803, 31.6167),
"kandahar": (65.7372, 31.6289),
"maidanshahr": (68.8407, 34.3611),
"kabul": (69.2075, 34.5553),
"peshawar": (71.5249, 34.0151),
"marwat": (70.9012, 32.6135)
}
print("City1       City2        Average Similarity")
print("---------------------------------------------")

pair_sim = {}

for i in range(len(dialects)):
    for j in range(i+1, len(dialects)):
        cityA = dialects[i]
        cityB = dialects[j]

        total_sim = 0
        count = 0
        for k in range(1, 24):
            total_sim += get_similarity(words[cityA][k], words[cityB][k])
            count += 1

        avg = total_sim / count
        pair_sim[(cityA, cityB)] = avg
        pair_sim[(cityB, cityA)] = avg

        print(f"{cityA:<11} {cityB:<11} {avg:.6f}")
import numpy as np
from scipy.cluster import hierarchy
import matplotlib.pyplot as plt

n = len(dialects)
distance_matrix = np.zeros((n, n))

for i in range(n):
    for j in range(i+1, n):
        sim = pair_sim[(dialects[i], dialects[j])]
        dist = 1 - sim
        distance_matrix[i][j] = dist
        distance_matrix[j][i] = dist

# condensed form for linkage
condensed = distance_matrix[np.triu_indices(n, k=1)]

Z = hierarchy.linkage(condensed, method='ward')

plt.figure(figsize=(14, 7))
hierarchy.dendrogram(Z, labels=dialects, leaf_rotation=90)
plt.title("Dialect Tree - How similar Pashto dialects are")
plt.xlabel("Cities/Dialects")
plt.ylabel("Distance (lower = more similar)")
plt.tight_layout()
plt.show()


plt.figure(figsize=(13, 10))

# plot points
for city in dialects:
    lon, lat = coords[city]
    plt.plot(lon, lat, 'ro')
    plt.text(lon + 0.1, lat, city, fontsize=10)

# draw lines
for i in range(len(dialects)):
    for j in range(i+1, len(dialects)):
        c1 = dialects[i]
        c2 = dialects[j]
        sim = pair_sim[(c1, c2)]

        lon1, lat1 = coords[c1]
        lon2, lat2 = coords[c2]

        plt.plot([lon1, lon2], [lat1, lat2], color='blue',
                 linewidth=sim*7, alpha=sim)

plt.title("Pashto Dialects Map - Closer dialects have thicker lines")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.grid(True)
plt.show()

