# -*- coding: utf-8 -*-
"""22P-9177_Sudais_Assignment-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfcH5B3xKMnqvekXmsV4c8D46Kn32RUQ

# Name: Sudais Touseef
# Roll No: 22P-9177
# Section: BCS-6B
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
import io

"""# Data Set Upload

"""

# ==== Step 1: Dataset Upload ====
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# Reading data based on file format
if file_name.endswith('.csv'):
    data = pd.read_csv(io.BytesIO(uploaded[file_name]))
elif file_name.endswith(('.xls', '.xlsx')):
    data = pd.read_excel(io.BytesIO(uploaded[file_name]))
else:
    raise ValueError("Unsupported file format. Only CSV/Excel files are accepted.")

"""# Task A: Data Cleaning and Analysis

"""

# ==== Step 2: Check for Essential Columns ====
required_columns = ['StartTime(UTC)', 'EndTime(UTC)']
missing_columns = [col for col in required_columns if col not in data.columns]
if missing_columns:
    print("ERROR: Missing essential columns:", missing_columns)
    print("Found columns:", data.columns.tolist())
    raise SystemExit("Execution halted due to missing columns")

# ==== Step 3: Handle Missing Data ====
# Replace common placeholders with NaN
data.replace(['N/A', 'NA', 'null', '0000-00-00 00:00:00'], pd.NA, inplace=True)

# Fill missing data by forward and backward filling
data.ffill(inplace=True)
data.bfill(inplace=True)

# Remove columns that still have missing values after filling
unfillable_columns = [col for col in data.columns if data[col].isnull().sum() > 0]
data.drop(columns=unfillable_columns, inplace=True)

print("\n=== Missing Data Handling ===")
print(f"Columns removed: {unfillable_columns}")
print(f"New dataset shape: {data.shape}")
print(f"Remaining missing values: {data.isnull().sum().sum()}")



# ==== Step 4: Date-Time Feature Engineering ====
# Clean and convert date columns to datetime format
for col in required_columns:
    data[col] = data[col].str.strip()
    data[col] = pd.to_datetime(data[col], format='mixed', utc=True, errors='coerce')
    data.dropna(subset=[col], inplace=True)

# Extract additional time-related features from the start time
data['Hour'] = data['StartTime(UTC)'].dt.hour
data['DayOfWeek'] = data['StartTime(UTC)'].dt.dayofweek
data['Month'] = data['StartTime(UTC)'].dt.month

# Calculate event duration in hours
data['Duration'] = (data['EndTime(UTC)'] - data['StartTime(UTC)']).dt.total_seconds() / 3600

"""# Task B: Visualization"""

# ==== Step 5: Data Visualization ====
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (12, 6)

def generate_plot(column):
    """Generate and explain a plot for the specified column"""
    print(f"\n=== Visualizing {column} ===")

    # Handle datetime columns with specific visualizations
    if pd.api.types.is_datetime64_any_dtype(data[column]):
        if column == 'StartTime(UTC)':
            data[column].dt.date.value_counts().sort_index().plot(color='purple')
            plt.title('Event Start Time Distribution')
            insight = "This shows how frequently events occurred over time"
        elif column == 'EndTime(UTC)':
            sns.histplot(data['Duration'], bins=24, kde=True, color='darkorange')
            plt.title('Event Duration Distribution (in Hours)')
            plt.xlabel('Duration (hours)')
            insight = "Most events last less than 4 hours"

    # Handle categorical variables
    elif data[column].dtype == 'object' or data[column].nunique() < 12:
        if column in ['City', 'County', 'AirportCode', 'ZipCode']:
            top10 = data[column].value_counts().head(10)
            top10.plot(kind='barh', color='darkcyan')
            plt.title(f'Top 10 {column} by Event Count')
            insight = f"Shows the most common locations for {column}"
        else:
            data[column].value_counts().plot(kind='bar', color='teal')
            plt.title(f'Distribution of {column}')
            insight = f"Displays the frequency of each {column} category"

    # Handle numerical columns
    elif np.issubdtype(data[column].dtype, np.number):
        if column in ['LocationLat', 'LocationLng']:
            plt.scatter(data['LocationLng'], data['LocationLat'],
                        alpha=0.1, c='darkred', rasterized=True)
            plt.title('Geospatial Distribution of Events')
            plt.xlabel('Longitude')
            plt.ylabel('Latitude')
            insight = "Shows where events are geographically concentrated"
        else:
            sns.histplot(data[column], kde=True, color='royalblue')
            plt.title(f'Distribution of {column}')
            insight = f"Shows the distribution of {column} values"

    else:
        print(f"No plot available for {column} ({data[column].dtype})")
        return

    plt.tight_layout()
    plt.show()
    print(f"Insight: {insight}")

# Visualize all columns except the derived features
print("\n\n=== Task B: Visualizations ===")
for col in data.columns:
    if col not in ['Hour', 'DayOfWeek', 'Month']:  # Skip derived columns
        generate_plot(col)

"""# Task C: Advanced Feature Engineering"""

# ==== Step 6: Advanced Feature Engineering ====
print("\n=== Advanced Feature Engineering ===")

# 1. Duration Feature
print("\n1. Duration Feature:")
print("- Calculated as the difference between StartTime and EndTime (already exists as 'Duration')")
print(data[['StartTime(UTC)', 'EndTime(UTC)', 'Duration']].head(2))

# 2. Season Feature
def map_to_season(month):
    """Assign a season based on the month"""
    if month in [12, 1, 2]: return 'Winter'
    elif month in [3, 4, 5]: return 'Spring'
    elif month in [6, 7, 8]: return 'Summer'
    else: return 'Fall'

data['Season'] = data['Month'].apply(map_to_season)

print("\n2. Season Feature:")
print("- Derived from the Month column")
print("Season distribution:")
print(data['Season'].value_counts())

# 3. Categorical Variable Encoding
print("\n3. Severity Encoding:")

# Show original severity categories
print("Original Severity Categories:", data['Severity'].unique())

# Label Encoding
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data['Severity_encoded'] = encoder.fit_transform(data['Severity'])

print("\nLabel Encoded Severity Values:")
print(pd.DataFrame({
    'Original': encoder.classes_,
    'Encoded': range(len(encoder.classes_))
}))

print("\nWhy Label Encoding?")
print("""
Label encoding was chosen for 'Severity' because:
- Severity is an ordinal variable (e.g., 'Light', 'Moderate', 'Severe')
- The encoding respects the inherent order of severity levels
- It reduces dimensionality compared to one-hot encoding
""")

print("\nFinal Dataset Features:")
print(data.columns.tolist())

"""# Task D: Advanced Analysis"""

# ==== Step 7: Advanced Data Analysis ====
print("\n=== Advanced Analysis ===")

# 1. Correlation Analysis
print("\n1. Precipitation and Duration Correlation:")
correlation = data['Precipitation(in)'].corr(data['Duration'])
print(f"Correlation coefficient: {correlation:.2f}")

# Heatmap for feature correlations
plt.figure(figsize=(10, 6))
numeric_columns = data.select_dtypes(include=np.number).columns
sns.heatmap(data[numeric_columns].corr(),
            annot=True,
            cmap='coolwarm',
            vmin=-1,
            vmax=1,
            mask=np.triu(np.ones_like(data[numeric_columns].corr())))
plt.title('Correlation Matrix of Features')
plt.show()

print("""
Correlation Insights:
- A slight positive correlation (0.18) between duration and precipitation suggests
  that longer events may experience more precipitation
- No strong linear relationship between precipitation and duration
""")

# 2. Outlier Detection
print("\n2. Outlier Detection for Precipitation:")

Q1 = data['Precipitation(in)'].quantile(0.25)
Q3 = data['Precipitation(in)'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5*IQR
upper_bound = Q3 + 1.5*IQR

outliers = data[(data['Precipitation(in)'] < lower_bound) |
                (data['Precipitation(in)'] > upper_bound)]

plt.figure(figsize=(10, 6))
sns.boxplot(x=data['Precipitation(in)'], color='skyblue')
plt.title('Precipitation Outliers Detection')
plt.xlabel('Precipitation (inches)')
plt.show()

print(f"""Outlier Analysis:
- Lower bound: {lower_bound:.2f} inches
- Upper bound: {upper_bound:.2f} inches
- {len(outliers)} outliers detected ({len(outliers)/len(data)*100:.1f}% of data)

Handling Outliers:
1. Consider retaining outliers as they represent rare but valid weather events
2. Employ robust statistics like median for more accurate analysis
3. Use log transformation to normalize skewed distributions
""")

# 3. Geospatial Event Distribution
print("\n3. Geospatial Distribution of Events:")

plt.figure(figsize=(14, 8))
plt.scatter(x=data['LocationLng'],
            y=data['LocationLat'],
            alpha=0.15,
            c='darkblue',
            s=10)
plt.title('Geospatial Distribution of Events')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.grid(True, alpha=0.3)
plt.show()

print("""Geospatial Insights:
- Events are clustered along the Eastern Seaboard and Midwest
- High density near cities like Chicago, Dallas, and Atlanta
- Sparse events in the Mountain West and Northern Plains
""")

"""Final Summary"""

# ==== Final Summary ====
print("\n=== Final Dataset Summary ===")
print(f"Total records: {len(data)}")
print(f"Dataset columns: {data.columns.tolist()}")
print("\nTime Range:")
print(f"Start Time: {data['StartTime(UTC)'].min()}")
print(f"End Time: {data['EndTime(UTC)'].max()}")